name:                useragents
version:             1.0.0
github:              "jappeace/useragents"
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2019 Jappie Klooster"

extra-source-files:
- Readme.md

ghc-options:
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Widentities
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

dependencies:
- base >= 4.7 && < 5
- text
- random-fu

library:
  source-dirs: src
executables:
  random-user-agent:
    main:                exe.hs
    source-dirs:         app
    dependencies:
    - useragents
